FROM centos:latest
LABEL tiset "tiosetia@detik.com"

ENV NGINX_VERSION 1.20.1
ENV OPENSSL_VERSION 1.1.1l

RUN CONFIG="\
    --prefix=/opt/nginx \
    --modules-path=/usr/lib/nginx/modules \
    --with-openssl=/usr/local/src/openssl-$OPENSSL_VERSION \
    --with-http_v2_module --with-http_ssl_module \
    --with-http_stub_status_module \
    --add-module=/usr/local/src/ngx_cache_purge \
    --add-module=/usr/local/src/nginx-push-stream-module \
    --with-http_dav_module \
    --with-file-aio \
    --with-threads \
    --with-stream \
    --add-module=/usr/local/src/headers-more-nginx-module \
    --add-module=/usr/local/src/ngx_http_lower_upper_case \
    --add-module=/usr/local/src/nginx_cookie_flag_module \
    " \
&& dnf install epel-release -y \
&& dnf update -y \
&& dnf -y install gcc \
    make \
    git \
    pcre-devel.x86_64 \
    zlib-devel.x86_64 \
&& mkdir -p /usr/local/src \
&& curl -fSL http://nginx.org/download/nginx-$NGINX_VERSION.tar.gz -o nginx.tar.gz \
&& curl -fSL https://www.openssl.org/source/openssl-$OPENSSL_VERSION.tar.gz -o openssl.tar.gz \
&& tar -zxC /usr/local/src -f nginx.tar.gz \
&& tar -zxC /usr/local/src -f openssl.tar.gz \
&& rm -rf nginx.tar.gz openssl.tar.gz \
&& git clone https://github.com/FRiCKLE/ngx_cache_purge.git /usr/local/src/ngx_cache_purge \
&& git clone https://github.com/openresty/headers-more-nginx-module.git /usr/local/src/headers-more-nginx-module \
&& git clone https://github.com/wandenberg/nginx-push-stream-module.git /usr/local/src/nginx-push-stream-module \
&& git clone https://github.com/replay/ngx_http_lower_upper_case.git /usr/local/src/ngx_http_lower_upper_case \
&& git clone https://github.com/AirisX/nginx_cookie_flag_module.git /usr/local/src/nginx_cookie_flag_module \
&& cd /usr/local/src/nginx-$NGINX_VERSION \
&& sed -i -e 's/\#define NGINX\_VERSION      \"'$NGINX_VERSION'\"/\#define NGINX\_VERSION      \"'ngx-test'\"/g' src/core/nginx.h \
&& ./configure $CONFIG \
&& make -j$(getconf _NPROCESSORS_ONLN) \
&& make install \
#&& strip /opt/nginx/sbin/nginx* \
#&& strip /usr/lib/nginx/modules/*.so \
&& rm -rf /usr/local/src/nginx-$NGINX_VERSION
RUN rm -rf /usr/local/src
